### ISSUE TITLE
Penumbra Black Plague not working

### ISSUE THREAD

**Issue by Asviix** [drtchops/asl#26]
I tried literally everything that was said in the readme, and with a bunch of differents version from Penumbra Black Plague And LiveSplit, I think the file dosen't work anymore, maybe you can help, in the meantime I'll try to search by myself.

(The timer is stuck at 0, so I guess it would be because of memory addresses not being the same in the GOG version (which I am using))

Would you mind sharing how did you found the addresses so I could adapt them myself ?

**Comment by Asviix** [comment]
(The timer is stuck at 0, so I guess it would be because of the game ?)

**Comment by Asviix** [comment]
Little bump in case you didn't saw it, it's a very annoying problem and I would love to update the file

**Comment by Asviix** [comment]
I got all the pointers I need, now can you tell me how I implement them in the script ?
Thanks

**Comment by drtchops** [comment]
@Asviix hi sorry, github never sent me any notifications. Is this still an issue? If you want to add in your pointers here you'll have to setup a version check to tell which ones to use. You can see an example of that here: https://github.com/drtchops/asl/blob/master/dishonored2.asl
